# Generated by Django 5.0.4 on 2024-05-06 17:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_op1_description_member_op1_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myapp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会員番号')),
                ('first_name', models.CharField(max_length=20, verbose_name='名前')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='入会日')),
                ('membership_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=10, verbose_name='会員種別')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('status', models.CharField(choices=[('active', '入会'), ('paused', '休会'), ('cancelled', '退会')], default='active', max_length=10, verbose_name='ステータス')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='継続期間')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='顔写真')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='月会費')),
                ('op1', models.BooleanField(default=False, verbose_name='オプション1')),
                ('op1_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='オプション1内容')),
                ('op1_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='オプション1料金')),
                ('op2', models.BooleanField(default=False, verbose_name='オプション2')),
                ('op2_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='オプション2内容')),
                ('op2_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='オプション2料金')),
                ('op3', models.BooleanField(default=False, verbose_name='オプション3')),
                ('op3_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='オプション3内容')),
                ('op3_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='オプション3料金')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
